# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: prs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # conda-forge channel packages first
  - conda-forge::r-base=4.0.3
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-data.table=1.13.0
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-rmarkdown=2.4
  - conda-forge::r-snakecase=0.11.0
  - conda-forge::r-sm=2.2_5.6 
  - conda-forge::r-r.utils=2.10.1
  - conda-forge::r-dt=0.16
  - conda-forge::r-htmltools=0.5.0
  - conda-forge::r-kableextra=1.2.1

  # bioconda channel packages second
  # defaults channel packages third
  - fonts-anaconda


  